// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC085ZF27ATnptu46p1EFUpzPLbKxANVIc',
    appId: '1:92300476582:web:f7b27e524253ea10383467',
    messagingSenderId: '92300476582',
    projectId: 'fir-crud-47b05',
    authDomain: 'fir-crud-47b05.firebaseapp.com',
    storageBucket: 'fir-crud-47b05.firebasestorage.app',
    measurementId: 'G-8BHTSZKNG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC16CEZcih9PsZaVBTG2R5tn7YbcwtIw6U',
    appId: '1:92300476582:android:64e2b749e6bf0749383467',
    messagingSenderId: '92300476582',
    projectId: 'fir-crud-47b05',
    storageBucket: 'fir-crud-47b05.firebasestorage.app',
  );
}
